### ISSUE TITLE
Grain labels missing

### ISSUE THREAD

**Issue by goelbenj** [Peterwarren623/GrainBoundaryDetection#1]
To whomever this may concern,

Is it possible to release the handmade label files for the grain boundary segmentation images? I would like to try training my own model on this data to replicate the results in the original paper.

**Comment by goelbenj** [comment]
Sorry, I did not see the second dataset with the artificial Voronoi data. This appears to contain the hand-labelled masks.

**Comment by Peterwarren623** [comment]
no worries, please reach out if you have any questions or want to discuss it Peterwarren62388@gmail.com

I do most of my coding for it on kaggle, we can exchange code and approaches on there too if you want

**Comment by goelbenj** [comment]
I'm investigating the generalizability of grain boundary semantic segmentation models, specifically, if a model trained on one type of material+grain samples can perform well on a never-before-seen metal+grain structure.

**Comment by Peterwarren623** [comment]
Very Cool! Check out a paper i wrote on using the voronoi artificial grain generation method, and I also have some Dice scores of various methods on this specific grain dataset: https://arxiv.org/abs/2307.05911
